version: '2'
services:
    jhipjwt-app:
        image: jhipjwt
        external_links:
            - jhipjwt-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipjwt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipjwt-mysql:
        extends:
            file: mysql.yml
            service: jhipjwt-mysql
